### ISSUE TITLE
Help needed: export labels to pdf

### ISSUE THREAD

**Issue by Raymond-Wijkhuizen** [mvdnbrk/myparcel-php-api#25]
I've a question about the exporting of labels. When user the "$myparcel->labels->get($id)" function it returns apparently the source code of the pdf. I'm really confused about how to convert this to a useable pdf download. Can you give me an example on how to go about this?
Many thanks in advance!

## My environment

Laravel 5.7, php 7.1, windows 10

**Comment by mvdnbrk** [comment]
You could just write the streamed content to a file:

```php
$contents = $myparcel->labels->get($id);
file_put_contents('label.pdf', $contents);
```

Or with Laravel:

```
$contents = $myparcel->labels->get($id);
Storage::put('label.pdf', $contents);
```

To download the pdf you can use the `download` method on the `Storage` facade in Laravel.

Hope that helps.

**Comment by Raymond-Wijkhuizen** [comment]
It works, many thanks!
