### ISSUE TITLE
Missing response attributes e.g. link_tracktrace

### ISSUE THREAD

**Issue by ZenoWebdev** [mvdnbrk/myparcel-php-api#39]
**Describe the bug**
Not all attributes from the api are present in the objects. When getting track and trace information some attributes are missing in the tracktrace object. link_tracktrace for example.

**To Reproduce**
Request tracktrace information: $myparcel->tracktrace->get('Shipment_id');

**Expected behavior**
Do not check if property exists in the setAttribute function in the HasAttributes class so all other properties can be used.

**Please complete the following information:**
 - Version of this package: 2.1.0
 - PHP Version: 7.4.0

**Comment by mvdnbrk** [comment]
Seems like this property was added this year.

Please feel free to open a PR to add the property you need to the respective class.
